### ISSUE TITLE
No available debug probes are connected

### ISSUE THREAD

**Issue by datnguyentien1981** [nihalpasham/rustBoot#12]
Dear Nihal

I have an issue related to pyocd driver for nrf52840 kit purchased on market (https://infocenter.nordicsemi.com/pdf/nRF52840_DK_User_Guide_v1.2.pdf)

I install pyocd driver and usb library on native ubuntu  18.4 and I can detect **pyocd version** and **SEGGER** device
```
home@home:~/Prj_Security/SourceCode/rustBoot-main$ pyocd --version
0.30.4.dev253
home@home:~/Prj_Security/SourceCode/rustBoot-main$ lsusb
Bus 002 Device 003: ID 1366:1015 SEGGER
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 17ef:6044 Lenovo
Bus 001 Device 003: ID 138a:003c Validity Sensors, Inc. VFS471 Fingerprint Reader
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
home@home:~/Prj_Security/SourceCode/rustBoot-main$
```

but when I compile Rustboot, It seems that there are no available debug probes are connected

```
home@home:~/Prj_Security/SourceCode/rustBoot-main$ pyocd list
**No available debug probes are connected**
```

```
home@home:~/Prj_Security/SourceCode/rustBoot-main$ rustup override set nightly

info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: override toolchain for '/home/home/Prj_Security/SourceCode/rustBoot-main' set to 'nightly-x86_64-unknown-linux-gnu'
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.59.0-nightly (f8abed9ed 2021-12-26)
home@home:~/Prj_Security/SourceCode/rustBoot-main$ cargo xtask build-sign-flash rustBoot nrf52840
Finished dev [unoptimized + debuginfo] target(s) in 0.90s
Running `target/debug/xtask build-sign-flash rustBoot nrf52840`
$ cargo build --release
    Finished release [optimized + debuginfo] target(s) in 0.59s
$ cargo build --release
    Finished release [optimized + debuginfo] target(s) in 0.04s
$ cargo build --release
    Finished release [optimized + debuginfo] target(s) in 0.08s
$ python3 convert2bin.py
$ python3 signer.py
Traceback (most recent call last):
  File "sign.py", line 28, in <module>
    from wolfcrypt import ciphers, hashes
ModuleNotFoundError: No module named 'wolfcrypt'
Traceback (most recent call last):
  File "sign.py", line 28, in <module>
    from wolfcrypt import ciphers, hashes
ModuleNotFoundError: No module named 'wolfcrypt'
$ pyocd erase -t nrf52 --mass
Waiting for a debug probe to be connected...
```
 
I hope that Rustboot can support below nrf52840 development kit (https://infocenter.nordicsemi.com/pdf/nRF52840_DK_User_Guide_v1.2.pdf)

If you have any solutions, please give me advice.

**Comment by nihalpasham** [comment]
`pycocd` doesn't depend on `rustBoot`. pyocd talks directly to the onboard-debugger present on the nrf52840-dk board. Can you try debugging some other firmware (instead of rustBoot), maybe use some sample `test blinky` firmware? 

I see you've run into another build-error i.e. the output above shows `ModuleNotFoundError: No module named 'wolfcrypt'`. Your probably missing the `wolfcrypt` library
